[package]
name = "oracle"
version = "0.0.1"
authors = ["Kubo Takehiro <kubo@jiubao.org>"]
build = "build.rs"

[dependencies]
lazy_static = "0.2"
try_from = "0.2.2"
chrono = "0.4"

[build-dependencies]
gcc = "0.3"
