[package]
name = "oracle"
version = "0.1.1"
authors = ["Kubo Takehiro <kubo@jiubao.org>"]
build = "build.rs"
repository = "https://github.com/kubo/rust-oracle"
license = "BSD-2-Clause"
keywords = ["oracle", "database"]
readme = "README.md"
description = "Oracle binding"

[dependencies]
lazy_static = "0.2"
try_from = "0.2.2"
chrono = { version = "0.4", optional = true }

[build-dependencies]
cc = "1.0"
